### ISSUE TITLE
The walrus operator prevents the package from working for Python 3.7.

### ISSUE THREAD

**Issue by LuisGarciaGomez** [openai/tiktoken#129] opened 2023-05-16 20:41 UTC
https://github.com/openai/tiktoken/blob/095924e02c85617df6889698d94515f91666c7ea/tiktoken/core.py#L116

**Comment by hauntsaninja** [comment] 2023-05-16 20:44
Duplicate of https://github.com/openai/tiktoken/issues/35

**Closed by hauntsaninja** 2023-05-16 20:44 UTC
