### ISSUE TITLE
Java Alternative

### ISSUE THREAD

**Issue by HarryBouch96** [openai/tiktoken#49] opened 2023-03-05 23:02 UTC
Does anyone know if a java alternative exists?

**Comment by hauntsaninja** [comment] 2023-03-06 08:01
Someone made Java bindings for tiktoken here: https://github.com/eisber/tiktoken

Note that that is not a repository maintained by OpenAI and I cannot personally vouch for it.

**Comment by jiangying000** [comment] 2023-03-18 04:18
need this

**Comment by tox-p** [comment] 2023-03-21 18:23
I was facing a similar issue and decided to port the part of tiktoken that I needed to java. Maybe this is helpful to you: https://github.com/knuddelsgmbh/jtokkit

Currently (0.1.0) it is quite limited and only supports encoding and decoding of r50k_base, p50k_base, p50k_edit and cl100k_base and I am just slowly starting with benchmarking and performance optimizations right now

**Comment by hauntsaninja** [comment] 2023-04-05 22:54
Thanks all! I'm closing this as a duplicate of https://github.com/openai/tiktoken/issues/97

**Closed by hauntsaninja** 2023-04-05 22:54 UTC
